spring:
  application:
    name: [project]-zuul

server:
  port: 8769

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: [project]-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: [project]-web-posts